language: node_js

node_js: stable

os:
  - linux

before_script:
   - npm install -g --silent @angular/cli

script:
   - ng build --prod
   - ng test --single-run

cache:
  directories: node_modules

branches:
  only:
  - master

notifications:
  email:
    on_failure: change
    on_success: change
