sudo: required

language: node_js

node_js: node

os:
  - linux

before_install:
  - npm install @angular/cli -g --silent
  - npm install coveralls --silent

install:
  - npm install --silent

script:
  - ng lint
  - ng test --code-coverage --watch false
  - ng e2e

cache:
  directories:
    - node_modules

notifications:
  email: false

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"