sudo: required

language: node_js

node_js: node

env:
- CI=true

os:
  - linux

before_install:
  - npm install @angular/cli -g --silent

addons:
- chrome: stable

install:
  - npm install --silent

script:
  - ng test
  - ng build --prod --aot

cache:
  directories:
    - node_modules

notifications:
  email: false

branches:
  only:
  - /.*/

after_success:
  - chmod +x ./publish.sh
  - ./publish.sh
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"