dist: trusty

sudo: false

language: node_js

node_js: node

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - npm install coveralls

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser

script:
  - npm run lint
  - xvfb-run -a ng test --code-coverage --watch=false --browser=ChromeNoSandbox
  - xvfb-run -a ng e2e --protractor-config=e2e/protractor-ci.conf.js

notifications:
  email: false

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"