matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

language: node_js

node_js: node

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

before_install:
  - npm install coveralls

install:
  - npm install

before_script:
  # use Chromium instead of Chrome
  - export CHROME_BIN=chromium-browser

script:
  - npm run lint

  # run unit tests
  - xvfb-run -a npm run test --code-coverage --single-run --no-progress --browser=ChromeNoSandbox

  # send coverage info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

  # run e2e tests
  - xvfb-run -a npm run e2e --no-progress --config=e2e/protractor-ci.conf.js

notifications:
  email: false

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"

env:
  secure: $COVERALLS_TOKEN