language: node_js

node_js: stable

os:
  - linux

before_install:
  - npm install -g --silent @angular/cli

addons:
- chrome: stable

install:
  - npm install

script:
  - karma start --single-run  --browsers ChromeHeadless
  - ng build --prod

cache:
  directories: node_modules

branches:
  only:
  - master

notifications:
  email:
    on_failure: change
    on_success: change
