sudo: required

language: node_js

node_js: node

env:
- CI=true

os:
  - linux

before_install:
  - npm install @angular/cli -g --silent

addons:
- chrome: stable

install:
  - npm install --silent

script:
  - ng test

cache:
  directories:
    - node_modules

before_deploy:
  - npm install netlify-cli -g --silent
  - ng build --prod --aot

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./dist
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: change

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"