language: node_js

node_js:
  - '8'

dist: trusty

sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - npm install coveralls

install:
  - npm install
  - npx lerna bootstrap

before_script:
  - export CHROME_BIN=chromium-browser

script:
  - npx lerna run lint --scope kauri-wallet
  - npx lerna run travis:test --scope kauri-wallet
  # - npx lerna run travis:e2e --scope kauri-wallet
  - npx lerna run prod --scope kauri-wallet
  - npx lerna run size --scope kauri-wallet


notifications:
  email: false

after_success:
  - cat packages/kauri-wallet/coverage/lcov.info | coveralls
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - "./send.sh success $WEBHOOK_URL"

after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"