language: node_js

sudo: required

node_js: "8"

os: osx

before_install:
  - npm install -g --silent @angular/cli

addons:
- chrome: stable

install:
  - npm install

script:
  - ng test
  - ng build --prod --aot

cache:
  directories:
    - node_modules

branches:
  only:
  - master

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
